apiVersion: v1
kind: Service
metadata:
  name: nephio-webui-ext
  namespace: nephio-webui
spec:
  type: NodePort
  selector:
    app: nephio-webui
  ports:
    - name: http
      port: 7007
      nodePort: 32555
      targetPort: http